stages:
  - test
  - release


lint:
  stage: test
  image: bellsoft/liberica-openjdk-alpine-musl:17@sha256:fe2ca302ae1225af4d482b726c0037a80a616604c4abe43a4bd7c6b44cf2245c
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
  needs: [ ]
  dependencies: [ ]
  cache:
    when: always
    key: $CI_COMMIT_REF_SLUG
    paths: [ .gradle-cache/wrapper, .gradle-cache/caches ]
  variables:
    GRADLE_USER_HOME: .gradle-cache
  script: ./gradlew --no-daemon --warning-mode all assemble ktlintCheck
  artifacts:
    when: always
    paths: [ build/reports/ ]


release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli@sha256:af74927a13c44668cf3741a8e3ef513cd4353703707c64b51b6f6ea98d3fefaf
  rules: [ { if: $CI_COMMIT_TAG } ]
  script: echo "Creating Release $CI_COMMIT_TAG"
  release:
    name: $CI_COMMIT_TAG
    description: Version $CI_COMMIT_TAG Commit $CI_COMMIT_REF_NAME Job $CI_JOB_ID
    tag_name: $CI_COMMIT_TAG
    ref: $CI_COMMIT_TAG
