name: Publish package to GitHub Packages

on:
  release:
    types: [ created ]

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6
      - uses: gradle/actions/wrapper-validation@v6
      - name: Publish package
        run: ./gradlew publishAllPublicationsToGitHubPackagesRepository
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
